# Project configuiration for Python tools.
[tool.black]
target-version = ["py310"]
line-length = 120

[tool.isort]
py_version = "310"
line_length = 120
profile = "black"
from_first = true
skip_gitignore = true

[tool.vulture]
min_confidence = 80
paths = ["."]
sort_by_size = true

[tool.ruff]
line-length = 120

[tool.mypy]
python_version = "3.10"
